[package]
name = "synchain"
version = "0.1.0"
authors = ["Alex Sarapulov <asarapulov@xdsoft.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
